const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const decode = require(require.resolve('decode-uri-component', { paths: [require.resolve('query-string')] }));
const query = require('query-string');
assert.equal(decode('ciao+mondo'), 'ciao mondo');
assert.equal(decode('%C3%A8%20ok'), 'è ok');
assert.equal(decode('%F0%9F%98%80'), '😀');
assert.equal(decode('%FF'), '%FF');
assert.equal(query.parse('name=%C3%A8+ok').name, 'è ok');
const result = spawnSync(process.execPath, ['-e', "const q=require('query-string'); if(q.parse('x='+ '%FF'.repeat(1500)).x !== '%FF'.repeat(1500)) process.exit(1)"], { timeout: 2000 });
assert.equal(result.error, undefined);
assert.equal(result.status, 0);
console.log('Decoder regression checks passed, including malformed URL timeout guard');
